Feature/arguments
akhmanova/ks-rate pull request #2
Opened 2020-12-06 11:54 UTC by KOHCEPBA

Добавил класс с параметрами запуска.
Встала необходимость для дальнейшего добавления каких-либо параметров запуска.

2020-12-06 13:14 UTC, akhmanova requested changes

2020-12-06 13:14 UTC, akhmanova commented on Readme.md
> +1. `--noGcs` - параметр для отключения модуля обращения
is the new flag mandatory for usage?

2020-12-06 13:22 UTC, akhmanova requested changes

2020-12-06 13:22 UTC, akhmanova commented on Readme.md
> +`java -jar ks-rate-1.0-SNAPSHOT.jar csvPath <Path_to_CSVFile> --noGcs`
Давай может лучше сделаем 
```suggestion
`java -jar ks-rate-1.0-SNAPSHOT.jar csvPath <Path_to_CSVFile> gcsAuth <Path_to_CSVFile`
```

Если есть параметр файла, тогда его и берём? Если неудобно такое сделать, я ок с тем, что есть.

2020-12-07 11:14 UTC, KOHCEPBA commented on Readme.md
> +1. `--noGcs` - параметр для отключения модуля обращения
По умолчанию он выключен. Если его не выключать, то:
а) Если нет файла авторизации, то приложение упадет с исключением.
б) Если нет необходимости добавлять данные в Google Storage, для экономии лимитов можно отключить модуль.

2020-12-07 11:14 UTC, KOHCEPBA commented on Readme.md
> +`java -jar ks-rate-1.0-SNAPSHOT.jar csvPath <Path_to_CSVFile> --noGcs`
В последующем PR будет видно для чего используются оба этих параметра.
Параметр "путь к файлу 'ауф'" нужен на случай, если таковой не прописан в переменных среды.
Если например нет желания/возможности прописать путь к файлу в переменной среды, то можно подтянуть файлик напрямую.

2020-12-08 08:13 UTC, akhmanova approved these changes

2020-12-08 08:13 UTC, merged